services:
  n8n:
    image: n8nio/n8n:2.6.4
    restart: always
    container_name: n8n-server
    ports:
      - "5678:5678"
    env_file:
      - .env
    extra_hosts:
      - "supabase.alphaagentx.com:35.236.134.87"
    volumes:
      - ./n8n-data:/home/node/.n8n
