services:
  n8n:
    image: n8nio/n8n:2.6.4
    restart: always
    container_name: n8n-server
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./n8n-data:/home/node/.n8n

  task-runners:
    build:
      context: .
      dockerfile: Dockerfile.runners
    container_name: n8n-runners
    restart: always
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-server:5679
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
      - N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT=0
      - N8N_RUNNERS_LAUNCHER_LOG_LEVEL=info
    depends_on:
      - n8n
